### ISSUE TITLE
Remove "-" Context Button

### ISSUE THREAD

**Issue by jpdevries** [jpdevries/revolution#1]
**Current State**
![image](https://f.cloud.github.com/assets/592335/1234092/a5683e46-295a-11e3-9d75-4cdaac4746d7.png)

**Proposed State**
![image](https://f.cloud.github.com/assets/592335/1234091/87984938-295a-11e3-98fd-b74e30e4a0f2.png)
- The plus button is not needed if the 4 create new buttons above will create within the current context. What if you want to create a non-current resource? Context Menus. Adding arguably simpler options without removing their predecessor adds complexity. We are not going to ship with three actions to the same thing all 50px from each other.
- A case can be made for the refresh button, but let's remember that action can be performed by
  - Context Menu
  - Main Refresh button
    The tree auto refreshes when using Quick Create/Update. Are we sure we need a third option?
- The "minus sign" icon is silly. It looks like a delete button. 

Why not still use carets to show open/close states?
![image](https://f.cloud.github.com/assets/592335/1234075/1c7e6dc2-2959-11e3-85ba-481ec1041be2.png)

**Comment by Mark-H** [comment]
I think there's added value in the "+" symbol (though for clients to use that, it would need to stand out more) when managing multi-context sites. It will load the proper defaults from the context and takes away the need for using the context menu (while keeping that available for power users).

Likewise, in larger multi-context sites, I'd say a per-context refresh is an added bonus too. I may not want to see the web context refreshed when I'm working in another one. 

Definitely lose the minus though.

**Comment by jpdevries** [comment]
Ya but we have
![image](https://f.cloud.github.com/assets/592335/1234128/162c1e34-295d-11e3-81be-a06b7a5230fc.png)

and
![image](https://f.cloud.github.com/assets/592335/1234129/404224f2-295d-11e3-89c1-1864491f770d.png)

**Comment by Mark-H** [comment]
Clients (or at least mine) don't understand right clicks. I could live with refresh being gone (clients don't typically do that stuff) but the + sign would be a great added value and something clients would figure out.

**Comment by jpdevries** [comment]
I understand that, and aren't opposed to some subtle 'shortcut' buttons (i agree the minus has to go). I do think that right now there are 3 separate actions and just want to make sure they are all necessary. This may be an example of what I've been thinking of as "2.3 bloat". Another example would be jQuery and ExtJS both being used. Just a hard fact when trying to maintain backwards compatibility while adding enhancements. 
![image](https://f.cloud.github.com/assets/592335/1234181/c43e0ac0-2960-11e3-84f7-501648d8c7c0.png)

![image](https://f.cloud.github.com/assets/592335/1234182/d0a74f4c-2960-11e3-8d94-1860d5aa788b.png)

![image](https://f.cloud.github.com/assets/592335/1234183/dd38b7fa-2960-11e3-98dd-6f983d9ce488.png)
